### ISSUE TITLE
Can't install wms, does not contain package

### ISSUE THREAD

**Issue by sonrebmax** [lmikolajczak/wms-tiles-downloader#12]
I tried to install in my debian 10

```
# go install github.com/lmikolajczak/wms-tiles-downloader@latest
go: downloading github.com/lmikolajczak/wms-tiles-downloader v2.0.0+incompatible
go: github.com/lmikolajczak/wms-tiles-downloader@latest: module github.com/lmikolajczak/wms-tiles-downloader@latest found (v2.0.0+incompatible), but does not contain package github.com/lmikolajczak/wms-tiles-downloader
```

debian 10, go version: 1.18.5

**Comment by lmikolajczak** [comment]
Hi @sonrebmax,

thanks for rising this issue.

Could you try `go install github.com/lmikolajczak/wms-tiles-downloader@v0.2.1` instead? It's the latest version of the package and it should solve the problem you encountered.

Let me know if that works 👍
