### ISSUE TITLE
How to download Tiles from x/y/z Tile URL?

### ISSUE THREAD

**Issue by eihabkhan** [lmikolajczak/wms-tiles-downloader#17]
I'm trying to download map tiles from the following endpoint [https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile](url) but I'm getting the following error
<img width="507" alt="Screen Shot 2023-02-27 at 4 52 05 PM" src="https://user-images.githubusercontent.com/6150471/221612385-62d231f5-f608-4816-996d-5206effce5a5.png">

The full URL with x/y/z is as follows
[https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}](url)

The command I'm trying to run
`./wms-tiles-downloader get --url https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/x/y/z --layer OSM_WMS --zoom 3 --bbox -90,-200,90,200`

**Comment by lmikolajczak** [comment]
Hi @eihabkhan,

This tool is dedicated for downloading tiles specifically from WMS (Web Map Services). The endpoint you're trying to use seems like a one from a REST server that returns tiles based on `x/y/z` params.


You can read more about WMS here: https://en.wikipedia.org/wiki/Web_Map_Service

Here is also an example of WMS request: 
```
http://<hostname>/<deploy_name>/com.esri.wms.Esrimap?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=Oceans,Countries,Cities&STYLES=&SRS=EPSG:4326&BBOX=-124,21,-66,49&WIDTH=600&HEIGHT=400&FORMAT=image/png
```
and the params it accepts: https://help.arcgis.com/en/arcims/10.0/mainhelp/mergedProjects/wms_connect/wms_connector/get_map.htm

**Comment by eihabkhan** [comment]
I see, thank you for the clarification.
