### ISSUE TITLE
how to tiles download

### ISSUE THREAD

**Issue by m6hdix** [lmikolajczak/wms-tiles-downloader#20]
Hi 
I hope you are doing well.

I am writing to ask how I can download maps from [https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile](https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/10/400/654.pbf)

I need to download these maps for a project I am working on.

Thank you for your help.

**Comment by lmikolajczak** [comment]
Downloading vector tiles is not supported.
