### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by nick-hunter** [lmikolajczak/wms-tiles-downloader#3]
I tried to install on my Mac using `go get -u github.com/Luqqk/wms-tiles-downloader...` and got this error `package github.com/Luqqk/wms-tiles-downloader...: invalid github.com/ import path "github.com/Luqqk"`

However `go get -u github.com/Luqqk/wms-tiles-downloader/...` worked. Should the readme be updated or is this something platform specific?

**Comment by easz** [comment]
btw, do we need a `go.mod` in the root folder?
`module github.com/Luqqk/wms-tiles-downloader`

**Comment by lmikolajczak** [comment]
Project has been refreshed and now supports modules. Working installation command can be found in README.md.
