### ISSUE TITLE
Allow to specify output path

### ISSUE THREAD

**Issue by erick-otenyo** [lmikolajczak/wms-tiles-downloader#7]
Hello. Thanks for this awesome tool.

I was wondering if there is a way to specify a custom output path where the tiles will be saved and not where the command is being invoked from ?

Thanks!

**Comment by lmikolajczak** [comment]
Hi @erick-otenyo!

Thanks for reaching out! Currently there's no such functionality. However, if you need it I can work on it. It should be pretty straightforward to add :)

Out of curiosity: do you actively use this tool?

**Comment by erick-otenyo** [comment]
Thanks @lmikolajczak for your quick response!

Yes I started to use it to generate tiles for large static WMS layers that don't change frequently over time, for example 100m resolution population layers that are rendered by a tool like mapserver. 

It will be great if we can have this configuration for the output directory, and also maybe an option for to configure the request timeout ? I noticed the default 5 seconds might not be enough for large datasets that might take time to render from the WMS server.

Thank you again!

**Comment by lmikolajczak** [comment]
@erick-otenyo

I implemented the features you requested and created new release: [v0.2.0](https://github.com/lmikolajczak/wms-tiles-downloader/releases/tag/v0.2.0) (Check it out to see what has been changed and how to use newly added flags).

You can also check this PR to check the code changes: https://github.com/lmikolajczak/wms-tiles-downloader/pull/8

Please let me know if it works as expected or if you run into any issues 😉

**Comment by erick-otenyo** [comment]
Works perfectly fine as expected! Thank you very much for your quick action. 
This can be closed now 🙂.
